name: Bingo_Workflow
on:
  push:
    branches:
      - githubActions_improvementD
jobs:

  # syntax_check_job:
  #   name: Check Syntax 
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v2
  #     - name: Linter Execution
  #       uses: github/super-linter@v3
  #       env:
  #         DEFAULT_BRANCH: githubActions_improvement
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         LINTER_RULES_PATH: /
  #         JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
  #         VALIDATE_JAVASCRIPT_ES: true
  #   outputs:
  #     status: ${{ job.status }}

  test_execution_job:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run test
        run: | 
            npm i
            npm run test
    outputs:
      status: ${{ job.status }}

  build_statics_job:
    name: Build
    runs-on: ubuntu-latest
    # needs: [syntax_check_job, test_execution_job] 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build app
        run: |
          npm i
          npm run buildDev
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: dist
    outputs:
      status: ${{ job.status }}
  
  deploy_job:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build_statics_job] 
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifact
      - name: Deploy Artifacts
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: bingoJavierSolerArtero.surge.sh
          project: .
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
    outputs:
      status: ${{ job.status }}

  email_job:
    name: Email
    runs-on: ubuntu-latest
    # needs: [syntax_check_job, test_execution_job, build_statics_job, deploy_job]
    needs: [test_execution_job, build_statics_job]
    if: ${{ always() }} 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Send email
        uses: ./.github/actions/mail_action 
        with:
          REPOSITORY: ${{ github.repository }}
          BRANCH: ${{ github.ref }}
          NAME_WORKFLOW: ${{ github.workflow }}
          OWNER: ${{ github.repository_owner }}
          ACTOR: ${{ github.actor }}

          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          PASSWORD: ${{ secrets.PASSWORD }}

          SYNTAX: ${{ needs.syntax_check_job.outputs.status }}
          BUILD: ${{ needs.build_statics_job.outputs.status }}
          TEST: ${{ needs.test_execution_job.outputs.status }}
          DEPLOY: ${{ needs.deploy_job.outputs.status }}

  update_readme_job:
    name: Update Readme
    runs-on: ubuntu-latest
    needs: [deploy_job]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Update README.md
        run: |
          sed -i '$d' README.md
          echo -e "\n\n ### Última versión desplegada el día: `date`" >> README.md
      - name: Save README.md
        run: |
          git config user.name ${{ secrets.GIT_USERNAME }}
          git config user.email ${{ secrets.GIT_EMAIL }}
          git commit -am "README.md Deploy update"
          git push origin githubActions_improvementD   