name: Bingo_Workflow
on:
  push:
    branches:
      - githubActions_improvementD
jobs:
  # syntax_check_job:
  #   name: Syntax check
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v2
  #     - name: Linter Execution
  #       uses: github/super-linter@v3
  #       env:
  #         DEFAULT_BRANCH: githubActions_improvement
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         LINTER_RULES_PATH: /
  #         JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
  #         VALIDATE_JAVASCRIPT_ES: true
  #   outputs:
  #     status: ${{ job.status }}

   test_execution_job:
    name: Test execution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run test
        run: | 
            npm i
            npm run test
    outputs:
      status: ${{ job.status }}